pipeline:
  sequence_length: 5
  train_cpu_lower_percentile: 0.10
  train_cpu_upper_percentile: 0.90

model:
  hidden_size: 64
  num_layers: 2
  dropout: 0.3

training:
  epochs: 100
  learning_rate: 0.001
  batch_size: 32

scheduler:
  factor: 0.5
  patience: 20
  min_lr: 0.000001
