pipeline:
  sequence_length: 5
  train_lower_percentile: 0.15
  train_upper_percentile: 0.85

model:
  hidden_size: 64
  num_layers: 2
  dropout: 0.3
  use_attention: true

training:
  epochs: 300
  learning_rate: 0.001
  batch_size: 32

scheduler:
  factor: 0.5
  patience: 30
  min_lr: 0.000001
